### ISSUE TITLE
subloader doesnt work on kodi 19

### ISSUE THREAD

**Issue by ananias47** [denimnani/service.subloader#12]
hi my friend

thank you for your great work

i am trying to use it on kodi 19 but it doesnt work 
i set it on open subtitles dialog and delay 10 seconds
on kodi 18.9 works great with the same settings

**Comment by denimnani** [comment]
Hi there do you have the latest version installed?
Make sure to install the repo to keep it up-to-date automatically.
Regarding the delay for kodi 18 and 19 you don't need it you can set it to 0 (unless you're running on a ultra low end device)

**Comment by ananias47** [comment]
hi my fried
yes i have installed your repo and i have the latest version 1.0.5

**Comment by ananias47** [comment]
[kodi.log](https://github.com/denimnani/service.subloader/files/6424489/kodi.log)

**Comment by denimnani** [comment]
Hi there,
Think I found the issue.


Here is your log info:
#####[SubLoader]##### Content path: https://23.download.real-debrid.com/d/GB4E2GAVCHEZA/Joker.2019.1080p.AMZN.WEB-DL.DDP5.1.H264-CMRG%5BEtHD%5D.mkv
#####[SubLoader]##### Content source: https://23.download.real-debrid.com/d/GB4E2GAVCHEZA/
#####[SubLoader]##### Total time: 2:01:45
#####[SubLoader]##### Default: opening search dialog


Subloader is set to open search dialog by default, not sure if you intended to do set it this way.
This option is only going to automatically open the subtitle dialog at the beginning of the video, it will not download anything.
In order to auto download the subtitle you need to change the setting to: “automatic subtitles”.
Another important thing, you have A4K Subtitles installed and is an awesome addon I use it myself, but if your intention is to set Subloader as your first option for auto subtitles you need to make sure the “auto option” in A4k Subs is disabled.

Please let me know if this fix’s your issue.

**Comment by ananias47** [comment]
hi my friend thank you again for your time 
yes i want only to pop up  the dialog and choose from there but it doesnt popup at all
in a4ksubtitles i disable the autosubs option
edit:a workaround i found is this
![screenshot00002](https://user-images.githubusercontent.com/6560173/117134490-54968f00-adae-11eb-9115-31280b864975.png)
![screenshot00000](https://user-images.githubusercontent.com/6560173/117134494-55c7bc00-adae-11eb-8fbb-cf95460e525d.png)

but if i set it on open subtitles dialog it doesnt work

**Comment by denimnani** [comment]
It seems we have a bug on the monitor.py

Can you please download directly from GitHub and try again.

![Sub](https://user-images.githubusercontent.com/49691619/117159253-08e8e300-adb8-11eb-965d-f5d8c8fdea49.png)

I add a possible fix for this, waiting on your feedback in order to push the update.

**Comment by ananias47** [comment]
yes my friend now works great thnx again

**Comment by denimnani** [comment]
Thank you @ananias47 you helped identifying this sneaky bug 😊.
The update is now rolling out.
